CREATE TABLE IF NOT EXISTS netology.orders
(
    id           integer          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date         timestamp without time zone,
    customer_id  integer
        constraint orders_customers_id_fk references netology.customers,
    product_name varchar(50)      NOT NULL,
    amount       double precision NOT NULL,
    PRIMARY KEY (id)
);