CREATE TABLE IF NOT EXISTS netology.customers
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50),
    surname character varying(50),
    age integer,
    phone_number character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT customers_pkey PRIMARY KEY (id)
);
